### ISSUE TITLE
When will the training and inference code be released?

### ISSUE THREAD

**Issue by Young2647** [AIGAnimation/CAMDM#1]
Thank you for your amazing work!

I've tried your Unity demo and it worked well! I can't wait to explore more about your work. I wonder when the training and inference code will be released.

Thanks again!

**Comment by ARuiChen** [comment]
Hi, thanks for your interest in our work! we plan to release all the code next week.

**Comment by Young2647** [comment]
> Hi, thanks for your interest in our work! we plan to release all the code next week.

Thank you for code-releasing so fast!! I will close the issue and wait.

**Comment by ARuiChen** [comment]
Hi @Young2647 , the training code has been released!

**Comment by ARuiChen** [comment]
the unity inference code has been released!
