### ISSUE TITLE
No need for multi-step denoising during inference?

### ISSUE THREAD

**Issue by warmshao** [AIGAnimation/CAMDM#2]
Directly predict x0?

**Comment by baopin132** [comment]
The loop is multi-step denoising.   https://github.com/AIGAnimation/CAMDM/blob/561c08bbfd6c9ea5239905101057dfc791caa55f/Unity/Assets/Demo/CAMDM/Diffusion.cs#L93

**Comment by warmshao** [comment]
thanks!
