### ISSUE TITLE
About retargeting the 100STYLE dataset with the Mixamo skeleton

### ISSUE THREAD

**Issue by 1279265865** [AIGAnimation/CAMDM#3]
Could you share the process about retargeting the 100STYLE dataset with the Mixamo skeleton? I am very curious about how you handled it. Thank you very much.

**Comment by Shimingyi** [comment]
We utilized a script in Blender with an add-on called [Auto-Rig-Pro](https://blendermarket.com/products/auto-rig-pro). This process involves some manual adjustments, but it's an important step to drive customized characters with different skeleton configurations. 

A new repository will be prepared this week to document and introduce the entire pipeline with more details. Hope it can help then.

**Comment by alphazhugit** [comment]
> We utilized a script in Blender with an add-on called [Auto-Rig-Pro](https://blendermarket.com/products/auto-rig-pro). This process involves some manual adjustments, but it's an important step to drive customized characters with different skeleton configurations.
> 
> A new repository will be prepared this week to document and introduce the entire pipeline with more details. Hope it can help then.

I've been looking forward to more detailed data processing instructions.🙂

**Comment by Shimingyi** [comment]
Hi @alphazhugit, Please check this repo: [ARP-Batch-Retargeting](https://github.com/Shimingyi/ARP-Batch-Retargeting?tab=readme-ov-file)
