### ISSUE TITLE
About the link to download dataset

### ISSUE THREAD

**Issue by gentlefress** [AIGAnimation/CAMDM#4]
Dear author,

This is a wonderful work and supervised me a lot! But I found a problem, that is I can't open the link https://1drv.ms/u/s!AtagzSrg3_hppdhGhO7hO6SfJx20LA?e=VGOE5E to download style dataset in the README.md. Can you give me a new link to download that ? Thank you very much!

**Comment by Shimingyi** [comment]
Hi, I checked it but it works in my side. Could you help check if OneDrive is accessible in your network? If no, then it might be the reason of GFW then I will share it with BaiduDisk for mainland user.

**Comment by Shimingyi** [comment]
Seems OneDrive is partially inaccessible from the mainland, so I prepared another download [link](https://pan.baidu.com/s/1jwymYGZ40DAryDz1kIDgXg?pwd=gwj6 ) with BaiduDisk for your convenience.

**Comment by gentlefress** [comment]
Thank you for your reply! These two links all work, I have solved that. Thank you again.
